# Numpy

NumPy is the core numerical library behind Pandas, Scikit-learn, TensorFlow, and PyTorch. Its main object, the ndarray, is a fixed-size, single-type array that stores data efficiently and runs operations quickly in optimized C code—much faster than Python lists.


## Learning Objectives
* Create NumPy arrays in different ways and inspect their shape, dtype, and ndim.

* Index and slice arrays (1D and 2D), including boolean masking.

* Replace Python loops with vectorized operations.

* Use broadcasting to combine arrays of different shapes.


## Key Topics
* Why NumPy matters: It’s the numerical foundation for Pandas, Scikit-learn, TensorFlow, and PyTorch.

* Array creation: array, zeros, ones, arange, linspace, random.

* Attributes & slicing: Access dimensions, data type, and elements with array[row, column].

* Vectorization: Apply operations to the whole array at once (faster and cleaner than loops).

* Boolean masking: Filter arrays based on conditions.

* Broadcasting: Combine arrays of different but compatible shapes (e.g., add a row vector to every row of a matrix).


### 1. Array creation

#### - From lists
np.array() converts lists\tuples into numby arrays


In [55]:
import numpy as np

arr1 =np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print(type(arr1))

arr2 =np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2)



[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### - Special array creation functions
* np.zeros(): creates array filed with 0's (takes shape tuple)
* np.ones(): creates array filed with 1's
* np.eye(): creates identity matrix (1's diagonal and 0's elsewhere)
* np.random(): creates an array that evenly spaced numbers over specified interval (defined by the start and stop value or the number of samples in it)
* np.linespace(): creates an array of evenly spaced values between two specified numbers (Instead of defining a step size, the total number of required values is specified)
 


In [56]:
import numpy as np

#zeros

zero = np.zeros((2,3))
print("zeros \n",zero)

#ones
one = np.ones((5,2))
print("ones \n",one)

#identity

identity = np.eye(3)
print("identity \n",identity )

#arange

r = np.arange(0, 10, 3)
print("arange\n",r)

# random

rnd = np.random.rand(3, 4)
print("random\n",rnd)

#linespace 

l = np.linspace(0, 10, 5)
print("linespace\n",l)


zeros 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
identity 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange
 [0 3 6 9]
random
 [[0.18663733 0.31365192 0.70076167 0.09795428]
 [0.51690682 0.87153992 0.12041591 0.28966766]
 [0.10962804 0.52979445 0.09563737 0.25503081]]
linespace
 [ 0.   2.5  5.   7.5 10. ]


### 2.Array Attributes, Indexing, and Slicing

 You can index and slice it like a list, but across multiple dimensions using commas—for example, array[row, column]

#### - Attributes
* shape: tuple show the dimension (rows,columns)
* ndim: number of dimension
* dtype: data type of elements
* size: total number of elements
* itemsize: memory used per element in bytes


In [57]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12], [13,14,15,16]])
print("array\n",arr)
print("shape\n",arr.shape)
print("size\n",arr.size)
print("no. of dim\n",arr.ndim)
print("data type\n",arr.dtype)
print("item size\n",arr.itemsize)
print("total bytes\n",arr.nbytes)


array
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
shape
 (4, 4)
size
 16
no. of dim
 2
data type
 int64
item size
 8
total bytes
 128


#### - Indexing
powerful feature that allows you to access and manipulate elements within an array using their index numbers.

In [58]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D array\n", arr1d)
print("first element\n", arr1d[0])
print("second element\n", arr1d[1])
print("last element\n", arr1d[-1])

#2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array\n", arr2d)
print("first row\n", arr2d[0])
print("second row\n", arr2d[1])
print("first element of first row\n", arr2d[0][0])
print("last element of last row \n",arr2d[-1][-1])



1D array
 [1 2 3 4 5]
first element
 1
second element
 2
last element
 5
2D array
 [[1 2 3]
 [4 5 6]]
first row
 [1 2 3]
second row
 [4 5 6]
first element of first row
 1
last element of last row 
 6


#### -Slicing
allows you to extract subarrays from larger arrays using a specific syntax. This technique is essential for data manipulation and analysis.

The basic syntax for slicing is:
[start:stop:step]

In [59]:
import numpy as np
# 1D array
arr1 = np.array([1,2,3,4,5,6])
print(arr1[1:4])  # slicing from index 1 to 3
print(arr1[:3])   # slicing from start to index 2

# 2D array
aar2 = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12], [13,14,15,16]])
print(aar2[-1, 1])   #slicing last row, second columns
print(aar2[0, 1:3])  # slicing row 0, columns 1 to 2
print(aar2[1, :2])   # slicing row 1, columns 0 to 1
print(aar2[:, 2])    # slicing all rows, column 2




[2 3 4]
[1 2 3]
14
[2 3]
[5 6]
[ 3  7 11 15]


### 3. Vectorized Operations
operations run on the whole array at once, without explicit loops. This makes code both faster and cleaner than element‑by‑element processing.

In [60]:

import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12], [13,14,15,16]])

print(arr*3)
print(arr+arr)
x= arr.mean()
print("grater than the mean\n",arr[arr>x])


[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
grater than the mean
 [ 9 10 11 12 13 14 15 16]


### 4. Brodcasting
apply operations across arrays of different but compatible shapes—like adding a scalar to every element or a 1D row to each row of a 2D array. Mastering it prevents shape‑mismatch errors and makes array work fluent.


In [62]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row    = np.array([10, 20, 30])
print(matrix + row) 

arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12], [13,14,15,16]])
print("before broadcasing\n",arr)
row2 = np.array([5,3,4,2])
arr2 = arr+row2    #[6,5,7,6],
                   #[10,9,11,10],
                   #[14,13,15,14],
                  # [18,17,19,18]
print("after brodcasting\n",arr2)



[[11 22 33]
 [14 25 36]]
before broadcasing
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
after brodcasting
 [[ 6  5  7  6]
 [10  9 11 10]
 [14 13 15 14]
 [18 17 19 18]]
