# Day 3 — Linear Algebra for ML
**Duration:** 8 hours

## Learning Objectives
- Represent data samples as vectors and datasets as matrices.
- Compute a dot product and explain why it is central to model prediction.
- Perform matrix multiplication and reason about resulting shapes.

## Key Topics
- Why linear algebra is the language of ML
- Vectors: one sample's features
- Matrices: a full dataset (samples × features)
- The dot product and how models predict with it
- Matrix multiplication and the shape-matching rule


## 3.1  Why Linear Algebra Is the Language of ML
Every dataset in ML is a matrix: rows are samples, columns are features. Every model's parameters are vectors or matrices, and training is a sequence of matrix operations.
You do not need to derive proofs, but you must understand what these objects are and how they combine — because that is literally what a model is doing internally.

## 3.2 Vectors
A vector is an ordered list of numbers — in ML, it usually represents one data sample's features, or one row of data.

In [42]:
import numpy as np

vec1=np.array([30,160,60]) #[age,height,weight]
print("vec1: ",vec1)


vec1:  [ 30 160  60]


* vector addition

In [43]:
v1=np.array([5,17,9])
v2 = np.array([26,8,2])
addv = v1+v2

print("vector addition: \n",addv)

vector addition: 
 [31 25 11]


* vector dot product

In [44]:
v1=np.array([5,17,9])
v2 = np.array([26,8,2])
vdot=np.dot(v1,v2)
print("the vectors dot product is : \n",vdot)

the vectors dot product is : 
 284


* vector norm : a vector's length or magnitude
  * L1 : It sums the absolute values of the vector components
  * L2 : It measures the straight-line distance from the origin to the point represented by the vector
  * infinity : It takes the largest absolute value among the vector's components

In [45]:
v1=np.array([5,17,9])
print("l1 norm: ",np.linalg.norm(v1 , ord=1))
print("l2 norm: ",np.linalg.norm(v1 , ord=2))
print("infinity norm: ",np.linalg.norm(v1 , np.inf))



l1 norm:  31.0
l2 norm:  19.87460691435179
infinity norm:  17.0


## 3.3 Matrices
A matrix is a 2D grid of numbers — a full dataset, where each row is a sample vector and each column is a feature.
Its shape is (rows, columns) = (samples, features).

In [46]:
matrix = np.array([[4,8,2],[3,7,4],[6,5,9]])
print("matrix:\n",matrix)

matrix:
 [[4 8 2]
 [3 7 4]
 [6 5 9]]


## 3.4 The Dot Product

The dot product multiplies two vectors element-by-element and sums the result, producing a single number.
This is the single most important operation in ML: a linear model's prediction is exactly the dot product of a feature vector and a weight vector, plus a bias.

In [47]:
vec1=np.array([5,8,2,4,7,3,1])
vec2=np.array([1,5,8,7,6,9,4])
dotvec=np.dot(vec1,vec2)
print("the dot product is:\n",dotvec)

the dot product is:
 162


## 3.5 Matrix Multiplication

Matrix multiplication applies the dot product across whole matrices at once, letting a model make predictions for every sample in a dataset in a single operation.

The rule: an `(m x n)` matrix times an `(n x p)` matrix gives an `(m x p)` matrix — the inner dimensions must match.

This is why shape mismatches are the most common error in ML code, and why understanding shapes is essential.

In [48]:
matrix1=np.array([[2,8,7,1],[5,6,2,3],[7,5,4,9]])
matrix2= np.array([[4,2,3],[5,2,6],[8,3,9],[1,3,6]])

matrixmul= matrix1 @ matrix2
print("matrix multiplication:\n",matrixmul)

matrix multiplication:
 [[105  44 123]
 [ 69  37  87]
 [ 94  63 141]]


* Transpose : switch the rows and columns of your matrix

In [49]:

m =np.array([[5,28,9,4],[5,7,54,42]])
print("matrix transpose: \n", m.transpose())

matrix transpose: 
 [[ 5  5]
 [28  7]
 [ 9 54]
 [ 4 42]]


* Determinant : The determinant of a square matrix is a special number that helps determine whether the matrix is invertible and how it transforms space.

In [50]:
m =np.array([[5,28,9],[5,7,54],[25,6,8]])
print("matrix deteminant: \n", np.linalg.det(m))

matrix deteminant: 
 34034.99999999997


* inversion : the process of finding a matrix that reverses the effect of another matrix during multiplication.

In [51]:
m =np.array([[5,28,9],[5,7,54],[5,2,6]])
print("matrix inversion: \n",np.linalg.inv(m))

matrix inversion: 
 [[-0.0107056  -0.0243309   0.2350365 ]
 [ 0.03892944 -0.00243309 -0.03649635]
 [-0.00405515  0.02108678 -0.01703163]]
